// Generated by Supabase for kwkhydnvbxvcfvhksxna after normalize_owned_cancellation_booking_ids.
// Schema only: no user rows, credentials or secrets. Regenerate; do not hand-edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      api_rate_limits: {
        Row: {
          attempts: number
          bucket: string
          subject_hash: string
          window_started_at: string
        }
        Insert: {
          attempts?: number
          bucket: string
          subject_hash: string
          window_started_at: string
        }
        Update: {
          attempts?: number
          bucket?: string
          subject_hash?: string
          window_started_at?: string
        }
        Relationships: []
      }
      arte_musical_application_period: {
        Row: {
          created_at: string | null
          end_time: string
          id: number
          musical_name: string
          start_time: string
        }
        Insert: {
          created_at?: string | null
          end_time: string
          id?: number
          musical_name: string
          start_time: string
        }
        Update: {
          created_at?: string | null
          end_time?: string
          id?: number
          musical_name?: string
          start_time?: string
        }
        Relationships: []
      }
      arte_musical_tickets: {
        Row: {
          booking_date: string
          created_at: string | null
          id: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request: string | null
          status: string
          student_id: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          booking_date?: string
          created_at?: string | null
          id?: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request?: string | null
          status?: string
          student_id: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          booking_date?: string
          created_at?: string | null
          id?: number
          name?: string
          seat_grade?: string
          selected_seats?: string[]
          special_request?: string | null
          status?: string
          student_id?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      bookings: {
        Row: {
          booking_date: string | null
          id: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request: string | null
          status: string | null
          student_id: string
        }
        Insert: {
          booking_date?: string | null
          id?: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request?: string | null
          status?: string | null
          student_id: string
        }
        Update: {
          booking_date?: string | null
          id?: number
          name?: string
          seat_grade?: string
          selected_seats?: string[]
          special_request?: string | null
          status?: string | null
          student_id?: string
        }
        Relationships: []
      }
      dead_poets_society_bookings: {
        Row: {
          booking_date: string
          created_at: string | null
          id: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request: string | null
          status: string
          student_id: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          booking_date?: string
          created_at?: string | null
          id?: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request?: string | null
          status?: string
          student_id: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          booking_date?: string
          created_at?: string | null
          id?: number
          name?: string
          seat_grade?: string
          selected_seats?: string[]
          special_request?: string | null
          status?: string
          student_id?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      performance_settings: {
        Row: {
          details: Json
          musical_id: string
          updated_at: string
        }
        Insert: {
          details: Json
          musical_id: string
          updated_at?: string
        }
        Update: {
          details?: Json
          musical_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "performance_settings_period_fkey"
            columns: ["musical_id"]
            isOneToOne: true
            referencedRelation: "arte_musical_application_period"
            referencedColumns: ["musical_name"]
          },
        ]
      }
      presale_access_keys: {
        Row: {
          created_at: string
          ends_at: string | null
          id: number
          is_active: boolean
          key_hash: string
          label: string | null
          max_seats_per_booking: number | null
          max_uses: number | null
          musical_id: string
          starts_at: string | null
          updated_at: string
          used_count: number
        }
        Insert: {
          created_at?: string
          ends_at?: string | null
          id?: number
          is_active?: boolean
          key_hash: string
          label?: string | null
          max_seats_per_booking?: number | null
          max_uses?: number | null
          musical_id: string
          starts_at?: string | null
          updated_at?: string
          used_count?: number
        }
        Update: {
          created_at?: string
          ends_at?: string | null
          id?: number
          is_active?: boolean
          key_hash?: string
          label?: string | null
          max_seats_per_booking?: number | null
          max_uses?: number | null
          musical_id?: string
          starts_at?: string | null
          updated_at?: string
          used_count?: number
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          contact_number: string | null
          created_at: string
          display_name: string | null
          id: string
          is_admin: boolean
          is_presale_user: boolean
          profile_completed_at: string | null
          student_id: string | null
          updated_at: string
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          contact_number?: string | null
          created_at?: string
          display_name?: string | null
          id: string
          is_admin?: boolean
          is_presale_user?: boolean
          profile_completed_at?: string | null
          student_id?: string | null
          updated_at?: string
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          contact_number?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          is_admin?: boolean
          is_presale_user?: boolean
          profile_completed_at?: string | null
          student_id?: string | null
          updated_at?: string
          username?: string | null
        }
        Relationships: []
      }
      rent_bookings: {
        Row: {
          booking_date: string
          created_at: string | null
          id: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request: string | null
          status: string
          student_id: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          booking_date?: string
          created_at?: string | null
          id?: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request?: string | null
          status?: string
          student_id: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          booking_date?: string
          created_at?: string | null
          id?: number
          name?: string
          seat_grade?: string
          selected_seats?: string[]
          special_request?: string | null
          status?: string
          student_id?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      "review-images": {
        Row: {
          created_at: string
          id: number
        }
        Insert: {
          created_at?: string
          id?: number
        }
        Update: {
          created_at?: string
          id?: number
        }
        Relationships: []
      }
      reviews: {
        Row: {
          content: string
          created_at: string
          deletion_token_hash: string | null
          id: number
          image_url: string | null
          musical_id: string
          password: string | null
          password_hash: string | null
          rating: number
          user_id: string | null
          user_name: string
        }
        Insert: {
          content: string
          created_at?: string
          deletion_token_hash?: string | null
          id?: number
          image_url?: string | null
          musical_id: string
          password?: string | null
          password_hash?: string | null
          rating?: number
          user_id?: string | null
          user_name: string
        }
        Update: {
          content?: string
          created_at?: string
          deletion_token_hash?: string | null
          id?: number
          image_url?: string | null
          musical_id?: string
          password?: string | null
          password_hash?: string | null
          rating?: number
          user_id?: string | null
          user_name?: string
        }
        Relationships: []
      }
      seat_status: {
        Row: {
          booking_id: number | null
          created_at: string | null
          floor: string
          id: number
          reserved_at: string | null
          seat_grade: string
          seat_id: string
          status: string | null
        }
        Insert: {
          booking_id?: number | null
          created_at?: string | null
          floor: string
          id?: number
          reserved_at?: string | null
          seat_grade: string
          seat_id: string
          status?: string | null
        }
        Update: {
          booking_id?: number | null
          created_at?: string | null
          floor?: string
          id?: number
          reserved_at?: string | null
          seat_grade?: string
          seat_id?: string
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "seat_status_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      toctoc_bookings: {
        Row: {
          booking_date: string
          created_at: string | null
          id: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request: string | null
          status: string
          student_id: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          booking_date?: string
          created_at?: string | null
          id?: number
          name: string
          seat_grade: string
          selected_seats: string[]
          special_request?: string | null
          status?: string
          student_id: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          booking_date?: string
          created_at?: string | null
          id?: number
          name?: string
          seat_grade?: string
          selected_seats?: string[]
          special_request?: string | null
          status?: string
          student_id?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_get_all_users: {
        Args: { p_limit?: number; p_offset?: number; p_search?: string }
        Returns: Json
      }
      book_musical_seats: {
        Args: {
          p_musical_id: string
          p_name: string
          p_seat_grade: string
          p_selected_seats: string[]
          p_special_request: string
          p_student_id: string
          p_user_id: string
        }
        Returns: Json
      }
      cancel_owned_reservation: {
        Args: {
          p_booking_id: number
          p_for_rebooking?: boolean
          p_source_id: string
          p_user_id: string
        }
        Returns: Json
      }
      check_rate_limit: {
        Args: {
          p_bucket: string
          p_limit: number
          p_subject_hash: string
          p_window_seconds: number
        }
        Returns: boolean
      }
      consume_presale_access_key: {
        Args: { p_key: string; p_musical_id: string }
        Returns: boolean
      }
      create_account_review: {
        Args: {
          p_content: string
          p_deletion_token: string
          p_image_url?: string
          p_musical_id: string
          p_rating: number
          p_user_id: string
          p_user_name: string
        }
        Returns: {
          content: string
          created_at: string
          id: number
          image_url: string
          musical_id: string
          rating: number
          user_name: string
        }[]
      }
      create_presale_access_key: {
        Args: {
          p_ends_at?: string
          p_key: string
          p_label?: string
          p_max_uses?: number
          p_musical_id: string
          p_starts_at?: string
        }
        Returns: number
      }
      create_review: {
        Args: {
          p_content: string
          p_deletion_token: string
          p_image_url?: string
          p_musical_id: string
          p_rating: number
          p_user_name: string
        }
        Returns: {
          content: string
          created_at: string
          id: number
          image_url: string
          musical_id: string
          rating: number
          user_name: string
        }[]
      }
      create_review_with_password_legacy: {
        Args: {
          p_content: string
          p_image_url?: string
          p_musical_id: string
          p_password: string
          p_rating: number
          p_user_name: string
        }
        Returns: {
          content: string
          created_at: string
          id: number
          image_url: string
          musical_id: string
          rating: number
          user_name: string
        }[]
      }
      delete_account: { Args: { p_user_id: string }; Returns: Json }
      delete_review_with_password: {
        Args: { p_password: string; p_review_id: number }
        Returns: boolean
      }
      delete_review_with_token: {
        Args: { p_deletion_token: string; p_review_id: number }
        Returns: boolean
      }
      get_account_fan_activity: { Args: { p_user_id: string }; Returns: Json }
      get_arte_membership_state: { Args: { p_user_id: string }; Returns: Json }
      get_presale_access_key_seat_limit: {
        Args: { p_key: string; p_musical_id: string }
        Returns: number
      }
      get_user_email_status: { Args: { p_user_id: string }; Returns: Json }
      is_current_user_admin: { Args: never; Returns: boolean }
      list_arte_admin_requests: { Args: { p_admin_id: string }; Returns: Json }
      record_account_fan_visit: { Args: { p_user_id: string }; Returns: Json }
      release_presale_access_key: {
        Args: { p_key: string; p_musical_id: string }
        Returns: boolean
      }
      review_arte_admin_request: {
        Args: { p_admin_id: string; p_approve: boolean; p_request_id: string }
        Returns: Json
      }
      save_admin_performance: {
        Args: {
          p_details: Json
          p_end: string
          p_musical_id: string
          p_start: string
        }
        Returns: undefined
      }
      save_profile_and_sync_bookings: {
        Args: {
          p_contact_number: string
          p_display_name: string
          p_student_id: string
          p_user_id: string
          p_username: string
        }
        Returns: Json
      }
      set_user_admin_status: {
        Args: {
          p_by_admin_id: string
          p_is_admin: boolean
          p_target_user_id: string
        }
        Returns: Json
      }
      set_user_presale_status: {
        Args: {
          p_by_admin_id: string
          p_is_presale: boolean
          p_target_user_id: string
        }
        Returns: Json
      }
      submit_arte_membership_request: {
        Args: { p_is_member: boolean; p_user_id: string }
        Returns: Json
      }
      sync_legacy_bookings: { Args: { p_user_id: string }; Returns: Json }
      update_profile: {
        Args: {
          p_avatar_url?: string
          p_display_name?: string
          p_student_id?: string
          p_user_id: string
        }
        Returns: Json
      }
      validate_presale_access_key: {
        Args: { p_key: string; p_musical_id: string }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
