CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.presale_access_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  musical_id TEXT NOT NULL,
  key_hash TEXT NOT NULL,
  label TEXT,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  max_uses INTEGER,
  max_seats_per_booking INTEGER,
  used_count INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT presale_access_keys_max_uses_positive CHECK (max_uses IS NULL OR max_uses > 0),
  CONSTRAINT presale_access_keys_max_seats_positive CHECK (max_seats_per_booking IS NULL OR max_seats_per_booking > 0),
  CONSTRAINT presale_access_keys_used_count_nonnegative CHECK (used_count >= 0),
  CONSTRAINT presale_access_keys_time_range CHECK (starts_at IS NULL OR ends_at IS NULL OR starts_at <= ends_at)
);

CREATE INDEX IF NOT EXISTS idx_presale_access_keys_musical_id
  ON public.presale_access_keys (musical_id);

CREATE INDEX IF NOT EXISTS idx_presale_access_keys_active_window
  ON public.presale_access_keys (musical_id, is_active, starts_at, ends_at);

ALTER TABLE public.presale_access_keys ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.presale_access_keys FROM PUBLIC;
REVOKE ALL ON TABLE public.presale_access_keys FROM anon;
REVOKE ALL ON TABLE public.presale_access_keys FROM authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.presale_access_keys TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.presale_access_keys_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.touch_presale_access_keys_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS touch_presale_access_keys_updated_at ON public.presale_access_keys;
CREATE TRIGGER touch_presale_access_keys_updated_at
  BEFORE UPDATE ON public.presale_access_keys
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_presale_access_keys_updated_at();

CREATE OR REPLACE FUNCTION public.create_presale_access_key(
  p_musical_id TEXT,
  p_key TEXT,
  p_label TEXT DEFAULT NULL,
  p_starts_at TIMESTAMPTZ DEFAULT NULL,
  p_ends_at TIMESTAMPTZ DEFAULT NULL,
  p_max_uses INTEGER DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_key_id BIGINT;
BEGIN
  IF p_musical_id IS NULL OR BTRIM(p_musical_id) = '' THEN
    RAISE EXCEPTION 'musical_id is required';
  END IF;

  IF p_key IS NULL OR LENGTH(BTRIM(p_key)) < 6 THEN
    RAISE EXCEPTION 'presale key must be at least 6 characters';
  END IF;

  INSERT INTO public.presale_access_keys (
    musical_id,
    key_hash,
    label,
    starts_at,
    ends_at,
    max_uses
  )
  VALUES (
    BTRIM(p_musical_id),
    extensions.crypt(BTRIM(p_key), extensions.gen_salt('bf')),
    NULLIF(BTRIM(p_label), ''),
    p_starts_at,
    p_ends_at,
    p_max_uses
  )
  RETURNING id INTO v_key_id;

  RETURN v_key_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.consume_presale_access_key(
  p_musical_id TEXT,
  p_key TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_key_id BIGINT;
BEGIN
  IF p_musical_id IS NULL OR p_key IS NULL OR BTRIM(p_key) = '' THEN
    RETURN FALSE;
  END IF;

  SELECT id
    INTO v_key_id
  FROM public.presale_access_keys
  WHERE musical_id = BTRIM(p_musical_id)
    AND is_active = TRUE
    AND key_hash = extensions.crypt(BTRIM(p_key), key_hash)
    AND (starts_at IS NULL OR NOW() >= starts_at)
    AND (ends_at IS NULL OR NOW() <= ends_at)
    AND (max_uses IS NULL OR used_count < max_uses)
  ORDER BY id
  FOR UPDATE SKIP LOCKED
  LIMIT 1;

  IF v_key_id IS NULL THEN
    RETURN FALSE;
  END IF;

  UPDATE public.presale_access_keys
  SET used_count = used_count + 1
  WHERE id = v_key_id;

  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.release_presale_access_key(
  p_musical_id TEXT,
  p_key TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_key_id BIGINT;
BEGIN
  IF p_musical_id IS NULL OR p_key IS NULL OR BTRIM(p_key) = '' THEN
    RETURN FALSE;
  END IF;

  SELECT id
    INTO v_key_id
  FROM public.presale_access_keys
  WHERE musical_id = BTRIM(p_musical_id)
    AND key_hash = extensions.crypt(BTRIM(p_key), key_hash)
    AND used_count > 0
  ORDER BY id
  FOR UPDATE SKIP LOCKED
  LIMIT 1;

  IF v_key_id IS NULL THEN
    RETURN FALSE;
  END IF;

  UPDATE public.presale_access_keys
  SET used_count = GREATEST(used_count - 1, 0)
  WHERE id = v_key_id;

  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_presale_access_key(
  p_musical_id TEXT,
  p_key TEXT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, extensions
AS $$
  SELECT p_musical_id IS NOT NULL
    AND p_key IS NOT NULL
    AND BTRIM(p_key) <> ''
    AND EXISTS (
      SELECT 1
      FROM public.presale_access_keys
      WHERE musical_id = BTRIM(p_musical_id)
        AND is_active = TRUE
        AND key_hash = extensions.crypt(BTRIM(p_key), key_hash)
        AND (starts_at IS NULL OR NOW() >= starts_at)
        AND (ends_at IS NULL OR NOW() <= ends_at)
        AND (max_uses IS NULL OR used_count < max_uses)
    );
$$;

CREATE OR REPLACE FUNCTION public.get_presale_access_key_seat_limit(
  p_musical_id TEXT,
  p_key TEXT
)
RETURNS INTEGER
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, extensions
AS $$
  SELECT max_seats_per_booking
  FROM public.presale_access_keys
  WHERE p_musical_id IS NOT NULL
    AND p_key IS NOT NULL
    AND BTRIM(p_key) <> ''
    AND musical_id = BTRIM(p_musical_id)
    AND is_active = TRUE
    AND key_hash = extensions.crypt(BTRIM(p_key), key_hash)
    AND (starts_at IS NULL OR NOW() >= starts_at)
    AND (ends_at IS NULL OR NOW() <= ends_at)
    AND (max_uses IS NULL OR used_count < max_uses)
  ORDER BY id
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.touch_presale_access_keys_updated_at() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_presale_access_key(TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.consume_presale_access_key(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.release_presale_access_key(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.validate_presale_access_key(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_presale_access_key_seat_limit(TEXT, TEXT) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.create_presale_access_key(TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ, INTEGER) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.consume_presale_access_key(TEXT, TEXT) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.release_presale_access_key(TEXT, TEXT) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.validate_presale_access_key(TEXT, TEXT) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.get_presale_access_key_seat_limit(TEXT, TEXT) FROM anon, authenticated;

GRANT EXECUTE ON FUNCTION public.create_presale_access_key(TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.consume_presale_access_key(TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_presale_access_key(TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_presale_access_key(TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_presale_access_key_seat_limit(TEXT, TEXT) TO service_role;

-- Example:
-- SELECT public.create_presale_access_key(
--   'dead-poets-society',
--   'ARTE-PRESALE-2026',
--   'staff preview',
--   NOW() - INTERVAL '1 day',
--   NULL,
--   30
-- );
